# https://pypi.org/project/dj-command/

[[commands]]
name = "md"
help = "Do the migration dance"
execute = "poetry run example/manage.py makemigrations && poetry run example/manage.py migrate"

[[commands]]
name = "up"
help = "Up all the things"
execute = "poetry install && poetry run example/manage.py migrate && poetry run example/manage.py runserver 0:8080"
long_running = true

[[commands]]
name = "r"
execute = "poetry run example/manage.py runserver 0:8080"
long_running = true

[[commands]]
name = "t"
execute = "poetry run nox -r && npm run-script test"

[[commands]]
name = "is"
execute = "poetry run isort --settings pyproject.toml ."
