[tool.poetry]
name = "django-unicorn"
version = "0.11.1"
description = "A magical full-stack framework for Django."
authors = ["Adam Hill <unicorn@adamghill.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/adamghill/django-unicorn/"
homepage = "https://www.django-unicorn.com"
keywords = ["django", "python", "javascript", "fullstack"]

[tool.poetry.dependencies]
python = "^3.6"
django = ">=3.0.0"
beautifulsoup4 = ">=4.8.0"
orjson = "^3.2.1"
shortuuid = "^1.0.1"
wrapt = "^1.12.1"
cachetools = "^4.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
black = "^19.10b0"
flake8 = "^3.8.3"
isort = "^5.0.9"
mypy = "<0.780"
django-stubs = "^1.5.0"
pytest-django = "^3.9.0"
bpython = "^0.19"
django-mock-queries = "^2.1.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.isort]
default_section = "THIRDPARTY"
known_first_party = ["django_unicorn", "example"]
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true
skip_glob = "*/migrations/*.py"
profile = "black"
