name: JavaScript CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up node
        uses: actions/setup-node@v1.4.3

      - name: Install node packages
        run: npm install
        
      - name: Test with ava
        run: npm run-script test
